version: '3'

services: 
    gateway: 
        restart: always
        build: 
            dockerfile: Dockerfile.dev
            context: ./gateway
        ports: 
            - '8080:80'
        depends_on:
            - client
            - api

    db:
        image: 'postgres:latest'
        restart: always
        environment: 
            POSTGRES_PASSWORD: example

    adminer:
        image: adminer
        restart: always
        ports:
            - 8090:8080
    
    redis:
        image: 'redis:latest'

    api:
        build: 
            dockerfile: Dockerfile.dev
            context: ./server
        volumes: 
            - /app/node_modules
            - ./server:/app 
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PG_USER=postgres
            - PG_PASSWORD=example
            - PG_HOST=db
            - PG_PORT=5432
            - PG_DATABASE=postgres
        restart: always
        depends_on: 
            - redis
            - db

    client:
        stdin_open: true
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app
        
    
    worker:
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        volumes: 
            - /app/node_modules
            - ./worker:/app
        depends_on: 
            - redis
        
